
% This is the configuration template file for individual analysis 
% _________________________________________________________________________
% 2009-2012 Stanford Cognitive and Systems Neuroscience Laboratory
%
% $Id: individualstats_config.m.template, Tianwen Chen, 2012-06-06 $
% -------------------------------------------------------------------------

% Please specify the data type of preprocessed images
% 'nii' for Nifti 4-D format, 'img' for Analyze 7.5 format
% If you would like the script to decide which type to use,
% uncomment the second line and comment the first line
paralist.data_type = 'nii';
% paralist.data_type = [''];

% Please specify the standard preprocessing pipeline you have used
paralist.pipeline = 'swcar';
%paralist.pipeline = 'shortened_swar';

% Please specify the raw data server
paralist.server_path = '/home/zhuyannan/data';
 
% Please specify the individualstats server
paralist.stats_path = '/home/zhuyannan/MGZ_new/individualstats_conditions_final_2s';

% Please specify the parent folder of the static data
% For YEAR data structure,      use the first one
% For NONE YEAR data structure, use the second one
paralist.parent_folder   = '';
% paralist.parent_folder = 'UCSFBoxer'

% Please specify the .txt file or a cell arry of subjects
% paralist.subjectlist =  {'17-01-10.1MGZ';'17-01-11.1MGZ';'17-01-11.2MGZ';
% '17-01-12.2MGZ';'17-01-13.1MGZ';'17-01-13.2MGZ';'17-02-13.2MGZ';
% '17-02-14.1MGZ';'17-02-14.2MGZ';'17-02-22.1MGZ';'17-02-22.2MGZ';'17-03-07.1MGZ';
% '17-03-07.2MGZ';'17-03-08.1MGZ';'17-03-08.2MGZ';'17-03-09.1MGZ';'17-03-09.2MGZ';
% '17-03-21.2MGZ';'17-03-22.1MGZ';'17-03-22.2MGZ';'17-03-23.1MGZ';
% '17-03-23.2MGZ';'17-03-24.1MGZ';'17-03-24.2MGZ';'17-03-28.1MGZ';'17-03-28.2MGZ';
% '17-03-29.1MGZ';'17-03-30.1MGZ';'17-03-30.2MGZ';};
% 
paralist.subjectlist =  {'17-01-10.1MGZ';'17-01-11.1MGZ';'17-01-11.2MGZ';'17-01-12.1MGZ';'17-01-12.2MGZ';
'17-01-13.1MGZ';'17-01-13.2MGZ';'17-02-13.1MGZ';'17-02-13.2MGZ';'17-02-14.1MGZ';
'17-02-14.2MGZ';'17-02-22.1MGZ';'17-02-22.2MGZ';'17-03-07.1MGZ';'17-03-07.2MGZ';
'17-03-08.1MGZ';'17-03-08.2MGZ';'17-03-09.1MGZ';'17-03-09.2MGZ';'17-03-21.1MGZ';
'17-03-21.2MGZ';'17-03-22.1MGZ';'17-03-22.2MGZ';'17-03-23.1MGZ';'17-03-23.2MGZ';
'17-03-24.1MGZ';'17-03-24.2MGZ';'17-03-28.1MGZ';'17-03-28.2MGZ';'17-03-29.1MGZ';
'17-03-29.2MGZ';'17-03-30.1MGZ';'17-03-30.2MGZ';};




% {'subjectlist_discard.txt'};
%paralist.subjectlist     = {'11-11-25.s100'};

% Please specify the .txt file or a cell array of exp_sessions
paralist.exp_sesslist = 'EL';

% Please specify the task design file (*.m)
% paralist.task_dsgn       = 'taskdesign_emotion_wly.m';
paralist.task_dsgn     = 'taskdesign_conspo2_EL_facenon2_voice2.m';

% Please specify the file holding contrasts
%paralist.contrastmat = ['']; 
paralist.contrastmat     = '/home/zhuyannan/toolbox/SPM/spm8_scripts/Mainfunctions/others/contrasts_EL_Cons_facenon_voice_MGZ.mat';


% Please specify the foler for preprocessed data via standard pipeline
paralist.preprocessed_folder = 'smoothed_spm8';

% Please specify the folder holding statistics results (below 'stats_spm' which is generated by default)
% If you include_volrepair = 1 below, set stats_folder = 'temp_stats';
%paralist.stats_folder = 'temp_stats';
paralist.stats_folder = 'EL_emo_mem_facenon2_voice2/stats_spm8_swcar';


% Please indicate whether to use head movements (1:Yes; 0:No)
paralist.include_mvmnt = 1;

% Please indicate whether it is based on VolRepair pipeline
% 1: use volrepair pipeline data for individual stats
% 0: use standard pipeline data
% If you set volrepair = 1, set up VolRepair section below
% If you set volrepair = 0, do not set up VolRepair section below 
paralist.include_volrepair = 0;

% -------------------------------------------------------------------------
% VolRepair Preprocessing Setup
% -------------------------------------------------------------------------

% Please specify the volrepair preprocessing pipeline
paralist.volpipeline = 'swavr';

% Please specify the volrepair preprocessed folder
paralist.volrepaired_folder = 'volrepair_spm8';

% Please specify the folder for VolRepaired data (swavrI*)
% the stats folder is under 'stats_spm8' folder (generated by default)
paralist.repaired_stats   = 'stats_spm8_VolRepair';

% -------------------------------------------------------------------------

% Please specify the folder holding batch templates
%paralist.template_path    = '/home/fmri/fmrihome/SPM/spm8_scripts/BatchTemplates';
paralist.template_path    = '/home/zhuyannan/toolbox/SPM/spm8_scripts/BatchTemplates'; %Shaozheng added

